version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: avivodb
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
